server:
  port: 9501

spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50   # 单个路径的最大连接数

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka8761:8761/eureka/, http://eureka8762:8762/eureka/