server:
  port: 9501

spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka8761:8761/eureka/, http://eureka8762:8762/eureka/