server:
  port: 9090

#redis集群
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/pomp_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password01!
  application:
    name: beta-spring
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  elasticsearch:
    cluster-nodes: 127.0.0.1:9300
    cluster-name: docker-cluster

async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 10
      queue_capacity: 10
      name:
        prefix: async-service-


article:
   id: 1
   author: dzq
   title: Hello
   content: hello world


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.dong.beta.controller.domain


#management:
#  endpoints:
#    web:
#      base-path: /actuator
#      exposure:
#        include: "*"

logging:
  config: classpath:logback-spring.xml
#
#logging:
#  level:
#    com.dong.beta.mapper: debug