server:
  port: 8888

#redis集群
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.0.1:3366/pomp_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password01!
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  application:
    name: beta-spring
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1     # 每次只能获取一条消息，处理完才能获取下一个

  elasticsearch:
    cluster-nodes: 127.0.0.1:9300
    cluster-name: docker-cluster

  redis:
    host: redis
    port: 6379
    database: 0

  kafka:
    bootstrap-servers: localhost:9092  # bootstrap-servers：连接kafka的地址，多个地址用逗号分隔
    consumer:
      group-id: myGroup
      enable-auto-commit: true
      auto-commit-interval: 100ms
      properties:
        session.timeout.ms: 15000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      retries: 1 #若设置大于0的值，客户端会将发送失败的记录重新发送
      batch-size: 16384 #当将多个记录被发送到同一个分区时， Producer 将尝试将记录组合到更少的请求中。这有助于提升客户端和服务器端的性能。这个配置控制一个批次的默认大小（以字节为单位）。16384是缺省的配置
      buffer-memory: 33554432 #Producer 用来缓冲等待被发送到服务器的记录的总字节数，33554432是缺省配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #关键字的序列化类
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #值的序列化类
    topic: dzq

async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 10
      queue_capacity: 10
      name:
        prefix: async-service-

article:
  id: 1
  author: dzq
  title: Hello
  content: hello world

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.dong.beta.controller.domain

#management:
#  endpoints:
#    web:
#      base-path: /actuator
#      exposure:
#        include: "*"

logging:
  config: classpath:logback-spring.xml

#logging:
#  level:
#    com.dong.beta.mapper: debug