server:
  port: 8762

eureka:
  instance:
    hostname: eureka8762
  client:
    # 禁止自己向自己注册
    registerWithEureka: false
    # 不去检索其他服务，因为服务注册中心本身的职责就是维护服务实例，不需要去检索其他服务
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8761:8761/eureka/